// <auto-generated />
using System;
using EMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EMSDbContext))]
    [Migration("20200226202847_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EMS.Core.Domain.Entities.ManagerAggregate.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Department = "Development",
                            EmployeeGuid = new Guid("0726769f-9be5-4f12-9a00-cf2eb89b7ac6"),
                            FirstName = "Employee",
                            LastName = "One",
                            ManagerId = 1,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Department = "HR",
                            EmployeeGuid = new Guid("7308c95c-474e-480a-93c4-8e60643b5403"),
                            FirstName = "Employee",
                            LastName = "Two",
                            ManagerId = 1,
                            Salary = 2000m
                        },
                        new
                        {
                            Id = 3,
                            Age = 27,
                            Department = "Security",
                            EmployeeGuid = new Guid("15892d7f-8dc0-473b-af85-4055bfaff724"),
                            FirstName = "Employee",
                            LastName = "Three",
                            ManagerId = 1,
                            Salary = 7000m
                        });
                });

            modelBuilder.Entity("EMS.Core.Domain.Entities.ManagerAggregate.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("ManagerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 24,
                            FirstName = "Manager",
                            LastName = "One",
                            ManagerGuid = new Guid("589d2818-d3d9-4a84-83ae-e9550c909693")
                        });
                });

            modelBuilder.Entity("EMS.Core.Domain.Entities.ManagerAggregate.Employee", b =>
                {
                    b.HasOne("EMS.Core.Domain.Entities.ManagerAggregate.Manager", null)
                        .WithMany("Employees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
